### ISSUE TITLE
Kinect2 Calibration

### ISSUE THREAD

**Issue by mwswartwout** [cwru-robotics/baxter-model-scan#2]
Have taken two groups of calibration images.

### 1st image set
Appears to not have good depth data for calibration. Occasionally will segfault when calibrating with this data set, appears similar to this issue: https://github.com/code-iai/iai_kinect2/issues/66. Initially was able to use the kinect2_viewer with these files, but now depth registration returns some enqueueError. Not planning on investigating this further.

### 2nd image set
Much better. Calibration works for objects that in the background, but is bad for objects in the foreground.

### Both image sets combined
Very bad calibration data.

### To Do:
- [x] Throw out first data set
- [x] Take further calibration images where object rotates on axis perpendicular to camera surface (requires remounting calibration image to tripod)
- [x] Take more images with calibration pattern closer to Kinect2
- [x] Test the two datasets independently and then combine to see if results improve
- [x] Research to find example point cloud images for Kinect2 to get point of comparison for what our data should look like

### 2nd Dataset Calibration Image
![calibratedwith2nddata](https://cloud.githubusercontent.com/assets/1334791/10052097/0eefbac4-61f3-11e5-9368-3359dc545b60.png)

### Both Datasets Calibration Image
![calibratedwithbothdatasets](https://cloud.githubusercontent.com/assets/1334791/10052098/0ef2406e-61f3-11e5-9b0d-543092f6e0a8.png)

### Uncalibrated Image
![uncalibrated](https://cloud.githubusercontent.com/assets/1334791/10052096/0eed09be-61f3-11e5-8148-84b6f99f0aa3.png)

**Comment by lucbettaieb** [comment]
Does it work???

**Comment by mwswartwout** [comment]
Lol no, I just figured I was never going to finish it.
