### ISSUE TITLE
Model Processing

### ISSUE THREAD

**Issue by jonathankoss** [cwru-robotics/baxter-model-scan#7]
- [x] Isolate points in a fixed box above the platform
 - [x] Find surface normal vectors
 - [ ] Normalize multiple pictures taken at the same angle [No longer needed]
 - [ ] Stitch together pictures from different angles to make a 3D model [No longer needed]

Below is the filtered image, what was filtered out, and then the original pcd:

![filtered pcd of table](https://cloud.githubusercontent.com/assets/7354893/10418529/95b918b6-702b-11e5-9f03-9c311e5d8001.png)
![outliers from pcd of table](https://cloud.githubusercontent.com/assets/7354893/10418530/95c8cf68-702b-11e5-8809-56fcf96bce3f.png)
![raw pcd of table](https://cloud.githubusercontent.com/assets/7354893/10418531/95c9b838-702b-11e5-92f5-495073c9ecc6.png)

**Comment by lucbettaieb** [comment]
@jonathankoss Do you think you'll still want to work on this stuff for your 399 next semester or are you done, you think?

**Comment by lucbettaieb** [comment]
Senior project has been over for a while.  Closing this.
